### ISSUE TITLE
Failed to load model data

### ISSUE THREAD

**Issue by katubug** [AbraXator/MoreSnifferFlowers#4]
Hi! I'm troubleshooting things in my latest.log and came across this:
```
[18:44:14] [Worker-ResourceReload-11/ERROR]: Failed to load model moresnifferflowers:models/item/cerulean_vine_patch.json
com.google.gson.JsonParseException: JSON data was null or empty
	at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:533) ~[client-1.20.1-20230612.114412-srg.jar%23798!/:?]
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23798!/:?]
	at net.minecraft.client.renderer.block.model.BlockModel.m_111461_(BlockModel.java:74) ~[client-1.20.1-20230612.114412-srg.jar%23798!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_246478_(ModelManager.java:110) ~[client-1.20.1-20230612.114412-srg.jar%23798!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

And thought you might like to know about it! Thanks for your time.

**Comment by AbraXator** [comment]
Hey, this error is caused by an old unused item, but it doesn't affect anything. I'll remove it in the next update. So no need to be worried about this error, and thanks!
