### ISSUE TITLE
Some crash

### ISSUE THREAD

**Issue by moonfather1** [AbraXator/MoreSnifferFlowers#9]
using dyespria (1-blue) gives me
```
[05:38:13] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@6703194c, suppressing error
java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class net.minecraft.world.item.DyeItem (net.minecraft.world.item.AirItem and net.minecraft.world.item.DyeItem are in module minecraft@1.20.1 of loader 'TRANSFORMER' @91da29b)
	at net.abraxator.moresnifferflowers.items.DyespriaItem.setDye(DyespriaItem.java:222) ~[moresnifferflowers-1.3.2.jar%23231!/:1.3.2] {re:classloading}
	at net.abraxator.moresnifferflowers.items.DyespriaItem.colorOne(DyespriaItem.java:99) ~[moresnifferflowers-1.3.2.jar%23231!/:1.3.2] {re:classloading}
	at net.abraxator.moresnifferflowers.items.DyespriaItem.m_6225_(DyespriaItem.java:78) ~[moresnifferflowers-1.3.2.jar%23231!/:1.3.2] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:585) ~[forge-1.20.1-47.1.43-universal.jar%23259!/:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:245) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:tetra.mixins.json:ItemStackMixin,pl:mixin:APP:canary.mixins.json:block.hopper.ItemStackMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:358) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tetra.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:classloading}
```

visually, block is painted and game didn't crash, network system swallowed it.
dyespria isn't spent, still got it in hand.

**Comment by Nikdo53** [comment]
Should be fixed in 1.4
